# Path to your oh-my-zsh installation.
export ZSH=$HOME/.dotfiles/zsh/oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="rstrong"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder
ZSH_CUSTOM=$HOME/.dotfiles/zsh/custom

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(docker golang github gitfast history-substring-search)

source $ZSH/oh-my-zsh.sh

# User configuration

export PATH="/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/packer:~/Library/Python/2.7/bin:~/.node/bin:$PATH:/usr/local/bin"
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

export PATH=$PATH:/usr/local/bin

export GOPATH=$HOME/go
export GOROOT=$HOME/Code/go
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

export PYTHONDONTWRITEBYTECODE=true

export PATH="$PATH:$HOME/.composer/vendor/bin"
if [[ "$OSTYPE" == "darwin"* ]]; then
    export PATH="$(brew --prefix homebrew/php/php70)/bin:$PATH"
fi

TIMEFMT=$'\nreal\t%*E\nuser\t%*U\nsys\t%*S'

setopt PROMPT_CR
setopt PROMPT_SP
export PROMPT_EOL_MARK=""

if [ -f ~/.dvm/dvm.sh ]; then
    source ~/.dvm/dvm.sh
fi

GPG_TTY=$(tty)
export GPG_TTY

dcleanup(){
    docker rm $(docker ps --filter status=exited -q 2>/dev/null) 2>/dev/null
    docker rmi $(docker images --filter dangling=true -q 2>/dev/null) 2>/dev/null
}

dcup(){
    docker-compose up -d
}

dcstop(){
    docker-compose stop -t 1
}

dcrm(){
    docker-compose stop -t 1
    docker-compose rm -f
}

updateos() {
    sudo apt update
    sudo apt upgrade
}

restartaudio() {
    pulseaudio -k
    sudo alsa force-reload
}

enableFuncKeys() {
    perl ~/.dotfiles/keyboard/k760_function_key.pl
}

build() {
    KEYBASE_USER=$(keybase status | head -n 1 | awk '{print $2}')
    http POST https://circleci.com/api/v1/project/$1/tree/$2?circle-token=$(cat /keybase/private/$KEYBASE_USER/circleci.token)
}

author() {
    git ls-files | xargs -n1 git blame --line-porcelain | sed -n 's/^author //p' | sort -f | uniq -ic | sort -nr
}

# The next line updates PATH for the Google Cloud SDK.
if [ -f /Users/rstrong/cloud-sdk/path.zsh.inc ]; then
  source '/Users/rstrong/cloud-sdk/path.zsh.inc'
fi

# The next line enables shell command completion for gcloud.
if [ -f /Users/rstrong/cloud-sdk/completion.zsh.inc ]; then
  source '/Users/rstrong/cloud-sdk/completion.zsh.inc'
fi

if [ -f ~/.bouncex/zsh_profile ]; then
	source ~/.bouncex/zsh_profile
fi

if [ -f ~/.gvm/scripts/gvm ]; then
#    source ~/.gvm/scripts/gvm
fi

function awsenv {
    n=$1
    export AWS_ENV=$1
    export AWS_KEYS=$n
    export AWS_ACCESS_KEY_ID=""
    export AWS_SECRET_ACCESS_KEY=""
    export AWS_REGION=""
    export BX_ENVIRONMENT=""
    export BX_ENVIRONMENTPREFIX=""
    awstoenv $n ~/.aws/credentials
}
function awstoenv {
    n=$1
    f=$2
    cat $f | awk '{if ($0 == "['$n']"){x=1} else if ($0 == "") {x=0} else if (x==1) {sub(/#/,"",$1); print "export "toupper($1)"="$3}}'
    eval $(cat $f | awk '{if ($0 == "['$n']"){x=1} else if ($0 == "") {x=0} else if (x==1) {sub(/#/,"",$1); print "export "toupper($1)"="$3}}')
}

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
